- name: copy gitlab docker files
  copy: src=gitlab.tar dest=/root
- name: load gitlab image
  command: docker load -i /root/gitlab.tar
- name: run gitlab container
  command: docker run --name gitlab -d -p {{gitlab_listen_port}}:80
           -p {{gitlab_shell_ssh_port}}:22 --env GITLAB_OMNIBUS_CONFIG="external_url '{{gitlab_external_url}}';
           gitlab_rails['gitlab_shell_ssh_port'] = {{gitlab_shell_ssh_port}}; nginx['listen_port'] = {{gitlab_listen_port}}"
           -v {{gitlab_volume}}/config:/etc/gitlab
           -v {{gitlab_volume}}/logs:/var/log/gitlab
           -v {{gitlab_volume}}/data:/var/opt/gitlab gitlab/gitlab-ce:latest